name: my portfolio
favicon: null
layout_spectrum: 0.99729
typography_spectrum: 0.2456
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.4705332741141319
  lightness: 0.9186453651636839
  saturation: 0.442412847885862
  rhythmicContrast: 0.19610500615090132
purpose: []
